
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Oct 29 14:34:57 JST 2014
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int FORALL = 5;
  public static final int RIGHTB = 7;
  public static final int GE = 22;
  public static final int UMINUS = 18;
  public static final int SIGMA = 4;
  public static final int MINUS = 14;
  public static final int SEMICOLON = 9;
  public static final int AND = 24;
  public static final int LEFTB = 6;
  public static final int RPAR = 11;
  public static final int OR = 25;
  public static final int COMMA = 8;
  public static final int DIV = 17;
  public static final int GEQ = 23;
  public static final int PLUS = 15;
  public static final int IF = 32;
  public static final int ENDWHILE = 38;
  public static final int ID = 28;
  public static final int LE = 20;
  public static final int EOF = 0;
  public static final int TRUE = 30;
  public static final int error = 1;
  public static final int EQ = 19;
  public static final int CON = 2;
  public static final int TIMES = 16;
  public static final int ENDIF = 35;
  public static final int RIGHTCB = 13;
  public static final int ELSE = 34;
  public static final int INDEX = 27;
  public static final int WHILE = 36;
  public static final int LET = 3;
  public static final int LEFTCB = 12;
  public static final int THEN = 33;
  public static final int LEQ = 21;
  public static final int LPAR = 10;
  public static final int STRINGLITERAL = 29;
  public static final int VALUE = 26;
  public static final int FALSE = 31;
  public static final int DO = 37;
}

