
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Oct 28 18:06:55 JST 2014
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int RIGHTB = 6;
  public static final int GE = 21;
  public static final int UMINUS = 17;
  public static final int SIGMA = 4;
  public static final int MINUS = 13;
  public static final int SEMICOLON = 8;
  public static final int AND = 23;
  public static final int LEFTB = 5;
  public static final int RPAR = 10;
  public static final int OR = 24;
  public static final int COMMA = 7;
  public static final int DIV = 16;
  public static final int GEQ = 22;
  public static final int PLUS = 14;
  public static final int IF = 31;
  public static final int ENDWHILE = 37;
  public static final int ID = 27;
  public static final int LE = 19;
  public static final int EOF = 0;
  public static final int TRUE = 29;
  public static final int error = 1;
  public static final int EQ = 18;
  public static final int CON = 2;
  public static final int TIMES = 15;
  public static final int RIGHTCB = 12;
  public static final int ENDIF = 34;
  public static final int ELSE = 33;
  public static final int INDEX = 26;
  public static final int WHILE = 35;
  public static final int LET = 3;
  public static final int LEFTCB = 11;
  public static final int THEN = 32;
  public static final int LEQ = 20;
  public static final int LPAR = 9;
  public static final int STRINGLITERAL = 28;
  public static final int VALUE = 25;
  public static final int FALSE = 30;
  public static final int DO = 36;
}

