
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Dec 05 18:03:54 JST 2014
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int FORALL = 5;
  public static final int RIGHTB = 9;
  public static final int GE = 24;
  public static final int UMINUS = 20;
  public static final int RIGHTAR = 7;
  public static final int SIGMA = 4;
  public static final int MINUS = 16;
  public static final int LEFTAR = 6;
  public static final int SEMICOLON = 11;
  public static final int AND = 26;
  public static final int LEFTB = 8;
  public static final int RPAR = 13;
  public static final int OR = 27;
  public static final int COMMA = 10;
  public static final int DIV = 19;
  public static final int GEQ = 25;
  public static final int PLUS = 17;
  public static final int IF = 34;
  public static final int ENDWHILE = 40;
  public static final int ID = 30;
  public static final int LE = 22;
  public static final int EOF = 0;
  public static final int TRUE = 32;
  public static final int error = 1;
  public static final int EQ = 21;
  public static final int CON = 2;
  public static final int TIMES = 18;
  public static final int ENDIF = 37;
  public static final int RIGHTCB = 15;
  public static final int ELSE = 36;
  public static final int INDEX = 29;
  public static final int WHILE = 38;
  public static final int LET = 3;
  public static final int LEFTCB = 14;
  public static final int THEN = 35;
  public static final int LEQ = 23;
  public static final int LPAR = 12;
  public static final int STRINGLITERAL = 31;
  public static final int VALUE = 28;
  public static final int FALSE = 33;
  public static final int DO = 39;
}

